Repository JuliaRobotics/RoME.jl, pull requests merged in 2020-05, with the labels that each got.

#277 move flux factor
  src/RoME.jl
  src/factors/flux/FluxModelsPose2Pose2.jl
  src/factors/flux/models/Pose2OdoNN_01.jl
Labels: factors, flux, maintenance

#278 prepare for DFG v0.8.0
  Project.toml
  src/RobotUtils.jl
Labels: maintenance, upstream

#280 add flatten function for flux json
  src/factors/flux/FluxModelsPose2Pose2.jl
  src/factors/flux/models/Pose2OdoNN_01.jl
Labels: enhancement, flux, serialization

#283 standardize to use solverParams
  examples/MITDatasetBatch.jl
  examples/MITDatasetFixedLag.jl
  examples/MITDatasetIncremental.jl
  examples/ManhattanDataset.jl
  examples/ManhattanDatasetBatch.jl
  examples/ManhattanDatasetFixedLag-FromBatch.jl
  examples/ManhattanDatasetFixedLag-MargOnly.jl
  examples/ManhattanDatasetFixedLag.jl
  examples/ManhattanDatasetIncremental.jl
  src/factors/BearingRange2D.jl
  test/HexagonalLightGraphs.jl
Labels: maintenance, standardization

#284 fix symbol prod change
  src/CanonicalGraphs.jl
Labels: deprecations

#285 fix Rotations dependency,
  test/testPartialXYH.jl
Labels: dependencies, maintenance, upstream

#286 updates and maintanence
  src/Deprecated.jl
  src/OdometryUtils.jl
  src/RoME.jl
  src/RobotUtils.jl
Labels: deprecations, feature, maintenance
