Repository JuliaRobotics/RoME.jl, pull requests merged in 2020-01, with the labels that each got.

#227 slight relax test
  test/testDynPose2D.jl
  test/threeDimLinearProductTest.jl
Labels: testing

#228 fix typo in compat section
  Project.toml
Labels: bug fix, compat, toml

#231 adjust cliq by cliq test
  test/testBeehive2D_CliqByCliq.jl
Labels: testing

#229 itegrating g2o support
  src/CanonicalGraphs.jl
  src/RoME.jl
  src/g2oParser.jl
  test/octagon.g2o
  test/runtests.jl
  test/testG2oParser.jl
Labels: enhancement, feature, feature request
