Repository JuliaRobotics/RoME.jl, pull requests merged in 2020-03, with the labels that each got.

#238 DFG v0.6 and remove labels
  Project.toml
  src/CanonicalGraphs.jl
  src/RoME.jl
  src/factors/BearingRange2D.jl
  src/factors/Polar.jl
  src/variables/DynPoint2D.jl
  src/variables/DynPose2D.jl
  src/variables/Point2D.jl
  src/variables/Point3D.jl
  src/variables/Pose2D.jl
  src/variables/Pose3D.jl
  test/BeehiveTestUtils.jl
  test/runtests.jl
  test/testBasicPose2Stationary.jl
  test/testBeehive2D_CliqByCliq.jl
  test/testDidsonFunctions.jl
  test/testDynPose2D.jl
  test/testFixedLagFG.jl
  test/testLoadBuildOrder.jl
  test/testPoint2Point2WorldBearing.jl
  test/testPose3Pose3NH.jl
  test/testpackingconverters.jl
  test/testpartialpose3.jl
  test/threeDimLinearProductTest.jl
Labels: deprecations, maintenance

#239 Duplicates pose2 point2 factors for parametric,
  src/factors/BearingRange2D.jl
  src/factors/Point2D.jl
  src/factors/Pose2D.jl
  src/factors/PriorPose2.jl
Labels: factors, parametric solution

#249 fix packing converters
  Project.toml
  test/testpackingconverters.jl
Labels: API, compat, deprecations, dfg, maintenance

#250 api to sortDFG
  examples/Beehive2D.jl
  src/RobotUtils.jl
Labels: API, deprecations, dfg, maintenance

#251 v0.6.1-rc1
  .github/workflows/TagBot.yml
  Project.toml
  examples/Beehive2D.jl
  src/RobotUtils.jl
  src/factors/BearingRange2D.jl
  src/factors/Point2D.jl
  src/factors/Pose2D.jl
  src/factors/PriorPose2.jl
  test/testpackingconverters.jl
Labels: release

#252 adding timestamps and maintenance
  Project.toml
  src/OdometryUtils.jl
  src/RoME.jl
  src/factors/MutablePose2Pose2.jl
  test/testDeadReckoningTether.jl
  test/testDeltaOdo.jl
Labels: API, compat, dfg, enhancement, maintenance, standardization

#254 revert to proper mpp constructor
  src/factors/MutablePose2Pose2.jl
  test/testDeadReckoningTether.jl
  test/testDeltaOdo.jl
Labels: factors, maintenance, regression

#253 v0.6.1-rc2
  Project.toml
  src/OdometryUtils.jl
  src/RoME.jl
  src/factors/MutablePose2Pose2.jl
Labels: release

#260 dont use EasyMessage
  Project.toml
  src/Deprecated.jl
  src/factors/Point2D.jl
  test/testpartialpose3.jl
Labels: deprecations, maintenance, upstream

#261 common SLAM front-end (experimental)
  src/Slam.jl
Labels: enhancement, upstream

#262 more canonical examples
  examples/OutlierVsMultimodal.jl
  src/CanonicalGraphs.jl
Labels: enhancement, example

#263 v0.6.2-rc1
  .travis.yml
  Project.toml
  examples/OutlierVsMultimodal.jl
  src/CanonicalGraphs.jl
  src/Deprecated.jl
  src/Slam.jl
  src/factors/Point2D.jl
  test/testpartialpose3.jl
Labels: release
