Repository JuliaRobotics/RoME.jl, pull requests merged in 2020-10, with the labels that each got.

#338 general maintenance
  Project.toml
  src/factors/flux/FluxModelsPose2Pose2.jl
  src/factors/flux/models/Pose2OdoNN_01.jl
  test/testPoint2Point2Init.jl
Labels: maintenance

#345 Improve Pose2Point2Bearing
  src/factors/Bearing2D.jl
Labels: bug fix

#328 use @defVariable for RoME Variable Types
  Project.toml
  src/RoME.jl
  src/variables/VariableTypes.jl
  src/variables/deprecated/DynPoint2D.jl
  src/variables/deprecated/DynPose2D.jl
  src/variables/deprecated/Point2D.jl
  src/variables/deprecated/Point3D.jl
  src/variables/deprecated/Pose2D.jl
  src/variables/deprecated/Pose3D.jl
  test/testDynPoint2D.jl
  test/testDynPose2D.jl
  test/testDynTarget2D.jl
  test/testPose2asLandm_DynPose2.jl
Labels: softtype, standardization

#346 cleanup pre-v0.10.0
  Project.toml
  src/RoME.jl
  src/factors/Pose2D.jl
  src/factors/flux/FluxModelsPose2Pose2.jl
  src/factors/flux/MixtureFluxPose2Pose2.jl
  src/factors/flux/models/Pose2OdoNN_01.jl
  test/testPoint2Point2.jl
Labels: compat, maintenance

#339 additional tests
  test/runtests.jl
  test/testTreeInitCommonMsg_IIF913.jl
Labels: testing

#347 update Hex BearingOnly example
  examples/Hexagonal2D_BearingOnly_SLAM.jl
Labels: example, maintenance

#343 Put back tree init unit tests and IIF comapt at v0.17
  .gitignore
  test/testBeehive2D_CliqByCliq.jl
  test/testBeehive2D_DoubleHexInit.jl
Labels: autoinit, compat, testing

#349 fix deprecations
  Project.toml
  test/testDidsonFunctions.jl
  test/testhigherdimroots.jl
  test/testpartialpose3.jl
Labels: deprecations, maintenance, testing, upstream
