Repository JuliaRobotics/RoME.jl, pull requests merged in 2020-08, with the labels that each got.

#317 remove depecations
  examples/Beehive2D.jl
  examples/Beehive2D_LandmarksManual.jl
  examples/DeadReckoningBranch.jl
  examples/FixedLagCircles.jl
  examples/MultiModalDensVid.jl
  examples/MultimodalRangeBearing.jl
  examples/RangesExampleTwo.jl
  examples/dev/CliqByCliqSolve.jl
  src/FactorGraphAnalysisTools.jl
  src/RoME.jl
  src/RobotUtils.jl
  src/TemporaryFunctionality.jl
  test/TestPoseAndPoint2Constraints.jl
  test/testBearing2D.jl
  test/testDeadReckoningTether.jl
  test/testDynPoint2D.jl
  test/testDynPose2D.jl
  test/testFixedLagFG.jl
  test/testInferdimWithBeehive2D.jl
  test/testManifoldsPose2Equivalent.jl
  test/testmultiplefeatures.jl
  test/threeDimLinearProductTest.jl
Labels: deprecations, maintenance

#318 add DynPose2DynPose2 and maintenance
  src/Deprecated.jl
  src/FactorGraphAnalysisTools.jl
  src/RoME.jl
  src/factors/DynPoint2D.jl
  src/factors/DynPose2D.jl
  src/factors/PartialPose3.jl
  src/factors/Pose2D.jl
  src/factors/PriorPose2.jl
  src/factors/VelPoint2D.jl
  src/factors/VelPose2D.jl
  test/testDynPose2D.jl
Labels: deprecations, enhancement, factors, maintenance, refactoring

#321 fast foward
  examples/Beehive2D.jl
  examples/Beehive2D_LandmarksManual.jl
  examples/DeadReckoningBranch.jl
  examples/FixedLagCircles.jl
  examples/MultiModalDensVid.jl
  examples/MultimodalRangeBearing.jl
  examples/RangesExampleTwo.jl
  examples/dev/CliqByCliqSolve.jl
  src/Deprecated.jl
  src/FactorGraphAnalysisTools.jl
  src/RoME.jl
  src/RobotUtils.jl
  src/TemporaryFunctionality.jl
  src/factors/DynPoint2D.jl
  src/factors/DynPose2D.jl
  src/factors/PartialPose3.jl
  src/factors/Pose2D.jl
  src/factors/PriorPose2.jl
  src/factors/VelPoint2D.jl
  src/factors/VelPose2D.jl
  test/TestPoseAndPoint2Constraints.jl
  test/testBearing2D.jl
  test/testDeadReckoningTether.jl
  test/testDynPoint2D.jl
  test/testDynPose2D.jl
  test/testFixedLagFG.jl
  test/testInferdimWithBeehive2D.jl
  test/testManifoldsPose2Equivalent.jl
  test/testmultiplefeatures.jl
  test/threeDimLinearProductTest.jl
Labels: fast-forward

#316 Towards Singleton Softtypes and getDimension getManifolds
  examples/Beehive2D.jl
  examples/RangesExampleTwo.jl
  src/RoME.jl
  src/variables/DynPoint2D.jl
  src/variables/DynPose2D.jl
  src/variables/Point2D.jl
  src/variables/Point3D.jl
  src/variables/Pose2D.jl
  src/variables/Pose3D.jl
  test/testBasicPose2Stationary.jl
  test/testManifoldsPose2Equivalent.jl
Labels: breaking changes, deprecations, maintenance, softtype

#322 Use DFGVariable nanosecond time in Dyn
  src/factors/DynPoint2D.jl
  src/factors/DynPose2D.jl
  src/factors/VelPoint2D.jl
  src/factors/VelPose2D.jl
  test/testDynPoint2D.jl
Labels: softtype

#323 Bumping DFG to v0.10
  Project.toml
Labels: compat, dependencies, toml

#327 workaround revise require bug
  src/RoME.jl
  src/factors/flux/FluxModelsPose2Pose2.jl
  test/testInferdimWithBeehive2D.jl
Labels: maintenance, upstream
