Repository JuliaRobotics/RoME.jl, pull requests merged in 2021-02, with the labels that each got.

#394 Update ci.yml to test on push
  .github/workflows/ci.yml
Labels: CI, testing

#393 Parametric CalcFactor updates and test
  Project.toml
  src/factors/BearingRange2D.jl
  src/factors/Point2D.jl
  src/factors/Pose2Point2.jl
  src/factors/PriorPose2.jl
  src/factors/Range2D.jl
  test/runtests.jl
  test/testParametric.jl
Labels: factors, needs documentation, parametric solution, standardization

#397 Update factors to return residual
  src/SensorModels.jl
  src/factors/Bearing2D.jl
  src/factors/BearingRange2D.jl
  src/factors/DynPoint2D.jl
  src/factors/DynPose2D.jl
  src/factors/MutablePose2Pose2.jl
  src/factors/PartialPose3.jl
  src/factors/Point2D.jl
  src/factors/Pose2D.jl
  src/factors/Pose2Point2.jl
  src/factors/Pose3Pose3.jl
  src/factors/PriorPose2.jl
  src/factors/Range2D.jl
  src/factors/VelPoint2D.jl
  src/factors/VelPose2D.jl
  test/testBearingRange2D.jl
  test/testParametric.jl
  test/testhigherdimroots.jl
Labels: breaking changes, factors, standardization

#403 backport api for accumulateDiscreteLocalFrame!,
  Project.toml
  src/OdometryUtils.jl
Labels: backport

#402 api for accumulateDiscreteLocalFrame!, #396
  src/OdometryUtils.jl
Labels: API, dead reckon tether, feature

#404 Fix accumulateDiscreteLocalFrame!
  src/OdometryUtils.jl
Labels: bug fix, dead reckon tether

#405 Fix accumulateDiscreteLocalFrame!
  src/OdometryUtils.jl
Labels: bug fix

#408 update tests for IIF v0.22 refactoring
  test/testPoint2Point2.jl
  test/testpackingconverters.jl
Labels: enhancement, needs testing, testing, upstream

#415 Update Project.toml, bump TU compat to v0.2.7
  Project.toml
Labels: bug fix, compat, upstream

#414 Update ci.yml to test on juila v1.6
  .github/workflows/ci.yml
Labels: CI

#411 test inflation on bearing range, #380
  Project.toml
  test/runtests.jl
  test/testInflation380.jl
  test/testPoint2Point2.jl
  test/testpartialpose3.jl
  test/threeDimLinearProductTest.jl
Labels: testing

#409 new flux factor test and update to CalcFactor
  attic/FluxModelsPose2Pose2.jl
  src/RoME.jl
  src/factors/flux/MixtureFluxPose2Pose2.jl
  test/runtests.jl
  test/testFluxModelsPose2.jl
Labels: API, breaking changes, refactoring, testing, upstream

#416 Consolidate Range Factors
  Project.toml
  src/factors/Range2D.jl
  test/TestPoseAndPoint2Constraints.jl
  test/testBearingRange2D.jl
  test/testInflation380.jl
  test/testParametric.jl
  test/testPoint2Point2.jl
  test/testPoint2Point2Init.jl
Labels: factors, maintenance, parametric solution, refactoring
