Repository JuliaRobotics/RoME.jl, pull requests merged in 2021-10, with the labels that each got.

#512 Fix (or try to) Pose3Pose3XYYaw
  src/factors/Bearing2D.jl
  src/factors/PartialPose3.jl
  test/_test_status.txt
  test/_test_status2.txt
  test/runtests.jl
  test/testBearing2D.jl
  test/testPartialPose3.jl
Labels: factors, manifolds, bug fix, partials

#509 Fixes and tests on PartialPose3, Bearing, and BearingRange Factors
  src/factors/Bearing2D.jl
  src/factors/BearingRange2D.jl
  src/factors/PartialPose3.jl
  test/TestPoseAndPoint2Constraints.jl
  test/runtests.jl
  test/testAccumulateFactors.jl
  test/testBearing2D.jl
  test/testBearingRange2D.jl
  test/testMultimodalRangeBearing.jl
  test/testPartialPose3.jl
  test/testPartialRangeCrossCorrelations.jl
Labels: testing, upstream, bug fix, potential bug, test all the things

#513 fix tests
  test/TestPoseAndPoint2Constraints.jl
  test/testPoint2Point2Init.jl
Labels: testing, bug fix

#514 more test adjustments
  test/testMultimodalRangeBearing.jl
  test/threeDimLinearProductTest.jl
Labels: testing

#515 allow helix generator to grow graph
  src/canonical/GenerateHelix.jl
  test/testGenerateHelix.jl
Labels: enhancement, testing

#516 adjust test partial correlations
  test/testPartialRangeCrossCorrelations.jl
Labels: testing

#517 standardize old ScalarFields test code
  Project.toml
  data/CanyonDEM.png
  src/RoME.jl
  src/services/RequiresImages.jl
  src/services/ScalarFields.jl
  test/runtests.jl
  test/testBearingRange2D.jl
  test/testScalarFields.jl
Labels: enhancement, standardization, testing, deferred, fields
