Repository JuliaRobotics/RoME.jl, pull requests merged in 2021-09, with the labels that each got.

#499 Update getSample to not return a tuple
  src/SensorModels.jl
  src/factors/Bearing2D.jl
  src/factors/BearingRange2D.jl
  src/factors/DynPoint2D.jl
  src/factors/DynPose2D.jl
  src/factors/MutablePose2Pose2.jl
  src/factors/PartialPose3.jl
  src/factors/PartialPriorPose2.jl
  src/factors/Point2D.jl
  src/factors/Point3Point3.jl
  src/factors/Pose2D.jl
  src/factors/Pose2Point2.jl
  src/factors/Pose3D.jl
  src/factors/Pose3Pose3.jl
  src/factors/PriorPose2.jl
  src/factors/Range2D.jl
  src/factors/VelPoint2D.jl
  src/factors/VelPose2D.jl
  test/testBearing2D.jl
  test/testBearingRange2D.jl
  test/testMultimodalRangeBearing.jl
  test/testPartialPose3.jl
  test/testhigherdimroots.jl
Labels: standardization, sampling, factors, user experience, WORK IN PROGRESS

#501 upstream api change solveTree! return only `tree`
  examples/Beehive2D.jl
  examples/Beehive2D_LandmarksManual.jl
  examples/FixedLagCircle6.jl
  examples/FixedLagCircles.jl
  examples/Hexagonal2D_SLAM.jl
  examples/MITDatasetBatch.jl
  examples/MITDatasetFixedLag.jl
  examples/MITDatasetIncremental.jl
  examples/ManhattanDataset.jl
  examples/ManhattanDatasetBatch.jl
  examples/ManhattanDatasetFixedLag-FromBatch.jl
  examples/ManhattanDatasetFixedLag-MargOnly.jl
  examples/ManhattanDatasetFixedLag.jl
  examples/ManhattanDatasetIncremental.jl
  examples/OutlierVsMultimodal.jl
  examples/RangesExample.jl
  examples/dev/CliqByCliqSolve.jl
  src/AdditionalUtils.jl
  src/Slam.jl
  src/canonical/GenerateHelix.jl
  test/HexagonalLightGraphs.jl
  test/TestPoseAndPoint2Constraints.jl
  test/testBasicPose2Stationary.jl
  test/testBearing2D.jl
  test/testBeehive2D_CliqByCliq.jl
  test/testBeehiveGrow.jl
  test/testDeadReckoningTether.jl
  test/testDynPoint2D.jl
  test/testDynPose2D.jl
  test/testDynTarget2D.jl
  test/testFixedLagFG.jl
  test/testInertialPose3.jl
  test/testInferdimWithBeehive2D.jl
  test/testInflation380.jl
  test/testPartialPriorYawPose2.jl
  test/testPartialRangeCrossCorrelations.jl
  test/testPoint2Point2.jl
  test/testPoint2Point2Init.jl
  test/testPose2Point2.jl
  test/testPose2asLandm.jl
  test/testPose2asLandm_DynPose2.jl
  test/testPose3Pose3NH.jl
  test/testSimpleHexPose3.jl
  test/testmultiplefeatures.jl
  test/threeDimLinearProductTest.jl
Labels: API, upstream, maintenance

#500 better dispatch on Pose3Pose3XYYaw
  src/factors/PartialPose3.jl
Labels: enhancement, performance

#503 Fix testParametricSimulated for Manifolds
  test/runtests.jl
  test/testParametricSimulated.jl
Labels: testing, parametric solution, manifolds

#502 tests must fail on fail with stacktrace
  test/runtests.jl
Labels: bug, testing, upstream, regression, inference

#504 more testing with tangent to points deconv fix
  src/RoME.jl
  test/runtests.jl
  test/testBasicPose2Conv.jl
  test/testBearing2D.jl
  test/testBearingRange2D.jl
  test/testFixedLagFG.jl
  test/testHexagonal2D_CliqByCliq.jl
  test/testParametricSimulated.jl
  test/testPartialRangeCrossCorrelations.jl
  test/testPoint2Point2Init.jl
  test/testTreeInitCommonMsg_IIF913.jl
  test/threeDimLinearProductTest.jl
Labels: testing, upstream, manifolds

#505 fixing tests in prep for v0.16.0
  src/canonical/GenerateBeehive.jl
  test/TestPoseAndPoint2Constraints.jl
  test/runtests.jl
  test/testBeehiveGrow.jl
  test/testDeadReckoningTether.jl
  test/testMultimodalRangeBearing.jl
  test/testPartialPriorYawPose2.jl
  test/testPoint2Point2Init.jl
Labels: enhancement, maintenance, manifolds

#507 fix test packing converters
  test/runtests.jl
  test/testpackingconverters.jl
Labels: testing, upstream, bug fix

#508 fix Beehive locality, and fix test Accumulate Means
  src/canonical/GenerateBeehive.jl
  test/runtests.jl
  test/testAccumulateFactors.jl
  test/testBasicPose2Conv.jl
Labels: testing, bug fix

#510 bug fix on Beehive and Honeycomb generators
  src/canonical/GenerateBeehive.jl
  src/canonical/GenerateHoneycomb.jl
  test/runtests.jl
Labels: example, canonical, bug fix
