Repository JuliaRobotics/RoME.jl, pull requests merged in 2021-04, with the labels that each got.

#434 new partial correlation test
  Project.toml
  src/factors/Range2D.jl
  test/runtests.jl
  test/testBeehive2D_CliqByCliq.jl
  test/testDynPose2D.jl
  test/testMultimodalRangeBearing.jl
  test/testPartialRangeCrossCorrelations.jl
  test/testpackingconverters.jl
Labels: maintenance, testing

#436 away from getManifolds, #244
  Project.toml
  src/Deprecated.jl
  src/RoME.jl
  src/TemporaryFunctionality.jl
  src/factors/DynPose2D.jl
  src/factors/Pose2Point2.jl
  src/variables/VariableTypes.jl
  src/variables/deprecated/DynPoint2D.jl
  src/variables/deprecated/Point2D.jl
  test/testBasicPose2Stationary.jl
  test/testInflation380.jl
  test/testManifoldsPose2Equivalent.jl
  test/testParametric.jl
  test/testPartialRangeCrossCorrelations.jl
Labels: API, compat, deprecations, maintenance, manifolds, standardization, testing

#437 fix getManifold calls
  src/TemporaryFunctionality.jl
Labels: API, bug fix, maintenance, manifolds

#419 Added scripts to compile sysimages including RoMEPlotting or its deps
  compileRoME/Gadfly/Project.toml
  compileRoME/Gadfly/compileRoMEGadflySysimage.jl
  compileRoME/Gadfly/precompile_triggers_gadfly.jl
  compileRoME/RoMEPlotting/Project.toml
  compileRoME/RoMEPlotting/compileRoMEPlottingSysimage.jl
  compileRoME/RoMEPlotting/precompile_triggers_plotting.jl
Labels: compiling, user experience
