Repository JuliaRobotics/RoME.jl, pull requests merged in 2021-07, with the labels that each got.

#462 lastpose is case sensitive
  Project.toml
  src/canonical/GenerateHelix.jl
Labels: bug fix, canonical

#449 move downstream functions from TU
  Project.toml
  src/Deprecated.jl
  src/OdometryUtils.jl
  src/RoME.jl
Labels: API, compat, dependencies, deprecations, refactoring, standardization

#464 Update Pose2 and BasicPose2Stationary tests
  src/TemporaryFunctionality.jl
  src/factors/BearingRange2D.jl
  src/factors/Pose2D.jl
  src/factors/PriorPose2.jl
  src/variables/VariableTypes.jl
  test/testBasicPose2Stationary.jl
  test/testInflation380.jl
Labels: API, WORK IN PROGRESS, breaking changes, enhancement, manifolds, testing, upstream

#466 Broken testsets
  test/runtests.jl
Labels: testing, workaround

#469 upstream calcHelix_T to IIF
  src/canonical/GenerateCircular.jl
  src/canonical/GenerateCommon.jl
  src/canonical/GenerateHelix.jl
  test/testGenerateHelix.jl
Labels: canonical, testing, upstream
