Repository JuliaRobotics/RoME.jl, pull requests merged in 2022-05, with the labels that each got.

#568 Revert Pose2Pose2 cache to test parametric
  src/factors/Pose2D.jl
  src/factors/PriorPose2.jl
  test/testParametric.jl
Labels: manifolds, bug fix, autodiff

#578 Restore parametric bearing range inflation test
  test/testInflation380.jl
Labels: testing, parametric solution

#580 v0.18.4-rc1
  Project.toml
  src/factors/Pose2D.jl
  src/factors/PriorPose2.jl
  test/testInflation380.jl
  test/testParametric.jl
Labels: release

#583 Add math to Pose2Pose2 docstring
  src/factors/Pose2D.jl
Labels: documentation, factors, manifolds
