Repository JuliaRobotics/RoME.jl, pull requests merged in 2022-06, with the labels that each got.

#586 Restore parametric tests
  test/runtests.jl
Labels: testing, parametric solution

#587 Bump v0.19 and manifolds upgrade compat
  Project.toml
Labels: maintenance, manifolds, compat

#592 initManual! -> initVariable! update
  examples/FixedLagCircles.jl
  examples/OutlierVsMultimodal.jl
  src/RobotUtils.jl
  test/testBasicPose2Conv.jl
  test/testBearing2D.jl
  test/testDidsonFunctions.jl
  test/testInflation380.jl
  test/testParametric.jl
  test/testPoint2Point2Init.jl
  test/threeDimLinearProductTest.jl
Labels: deprecations, maintenance

#593 Parametric SE(2) and SE(3)
  src/factors/Pose3D.jl
  src/factors/Pose3Pose3.jl
  test/runtests.jl
  test/testParametric.jl
  test/testPose3.jl
Labels: testing, parametric solution, manifolds, test all the things

#595 Update for deprecated useCalcFactor
  test/testParametric.jl
Labels: deprecations, parametric solution, maintenance

#597 MJL v0.8.11 compat bound
  Project.toml
Labels: manifolds, compat
