Repository JuliaRobotics/RoME.jl, pull requests merged in 2022-07, with the labels that each got.

#598 Fix preambleCache bug and add PriorPoint3 function for parametric
  src/factors/Bearing2D.jl
  src/factors/DynPose2D.jl
  src/factors/Point3D.jl
Labels: parametric solution, bug fix, cache

#599 ArrayPartition upgrade
  .github/workflows/ci.yml
  Project.toml
  src/Deprecated.jl
  src/ExportAPI.jl
  src/RoME.jl
  src/factors/Bearing2D.jl
  src/factors/BearingRange2D.jl
  src/factors/PartialPose3.jl
  src/factors/Pose2D.jl
  src/factors/PriorPose2.jl
  src/factors/Range2D.jl
  src/factors/VelPose2D.jl
  src/variables/Local_Manifold_Workaround.jl
  src/variables/VariableTypes.jl
  test/TestPoseAndPoint2Constraints.jl
  test/testBasicPose2Conv.jl
  test/testBasicPose2Stationary.jl
  test/testBearing2D.jl
  test/testBearingRange2D.jl
  test/testFixedLagFG.jl
  test/testHexagonal2D_CliqByCliq.jl
  test/testParametric.jl
  test/testParametricSimulated.jl
  test/testPartialPose3.jl
  test/testPartialPriorYawPose2.jl
  test/testPose2Point2.jl
  test/testPose3Pose3NH.jl
  test/testTreeInitCommonMsg_IIF913.jl
  test/threeDimLinearProductTest.jl
Labels: standardization, maintenance, manifolds

#600 oops, bugfix
  src/variables/Local_Manifold_Workaround.jl
  test/testParametric.jl
  test/testPose2Point2.jl
Labels: bug fix

#603 Deprecation updates
  .github/workflows/ci.yml
  src/Deprecated.jl
  src/RobotUtils.jl
  src/factors/Pose2D.jl
  src/variables/Local_Manifold_Workaround.jl
  test/runtests.jl
Labels: deprecations, maintenance
