Repository JuliaRobotics/RoME.jl, pull requests merged in 2022-09, with the labels that each got.

#621 Fix test for br solve for pose, PartialPriorYawPose2 test, and cleanup Pose2Point2Bearing
  src/factors/Bearing2D.jl
  src/factors/PartialPriorPose2.jl
  test/testBearing2D.jl
  test/testBearingRange2D.jl
  test/testPartialPriorYawPose2.jl
  test/testPoint2Point2.jl
  test/testPoint2Point2Init.jl
Labels: testing, bug fix

#624 Fix and test packing Pose3Pose3Rotation
  src/ExportAPI.jl
  src/factors/PartialPose3.jl
  test/testpackingconverters.jl
Labels: testing, factors, serialization, bug fix, test all the things

#625 v0.20.1-rc1
  .github/workflows/CompatHelper.yml
  .github/workflows/ci.yml
  Project.toml
  src/ExportAPI.jl
  src/factors/Bearing2D.jl
  src/factors/BearingRange2D.jl
  src/factors/PartialPose3.jl
  src/factors/PartialPriorPose2.jl
  src/factors/Pose2D.jl
  src/factors/PriorPose2.jl
  src/g2oParser.jl
  test/runtests.jl
  test/testBearing2D.jl
  test/testBearingRange2D.jl
  test/testG2oParser.jl
  test/testParametric.jl
  test/testPartialPose3.jl
  test/testPartialPriorYawPose2.jl
  test/testPoint2Point2.jl
  test/testPoint2Point2Init.jl
  test/testpackingconverters.jl
Labels: release

#627 Bump for IIF v0.31
  .github/workflows/ci.yml
  Project.toml
Labels: compat

#630 remove fmd usage
  attic/FluxModelsPose2Pose2.jl
  src/factors/DynPoint2D.jl
  src/factors/DynPose2D.jl
  src/factors/VelPoint2D.jl
  src/factors/VelPose2D.jl
  src/factors/flux/MixtureFluxPose2Pose2.jl
Labels: deprecations, maintenance

#629 add SnoopPrecompile step
  Project.toml
  src/AdditionalUtils.jl
  src/RoME.jl
Labels: enhancement, performance, compat, compiling

#632 precompile Pose3 parametric solve too
  src/AdditionalUtils.jl
  src/RoME.jl
Labels: parametric solution, performance, compiling

#633 new utils, better code placement
  NEWS.md
  Project.toml
  src/Deprecated.jl
  src/ExportAPI.jl
  src/RoME.jl
  src/entities/RobotDataTypes.jl
  src/entities/SpecialDefinitions.jl
  src/factors/RangeAzimuthElevation.jl
  src/factors/SensorModels.jl
  src/legacy/BayesTracker.jl
  src/legacy/CameraModel.jl
  src/legacy/NavigationSystem.jl
  src/legacy/Slam.jl
  src/services/AdditionalUtils.jl
  src/services/BearingRangeUtils.jl
  src/services/FactorGraphAnalysisTools.jl
  src/services/FixmeManifolds.jl
  src/services/ManifoldUtils.jl
  src/services/OdometryUtils.jl
  src/services/RobotUtils.jl
  src/services/SimulationUtils.jl
  src/services/g2oParser.jl
  test/testPose3.jl
Labels: enhancement, deprecations, maintenance, manifolds

#634 v0.21.1-rc1
  NEWS.md
  Project.toml
  src/Deprecated.jl
  src/ExportAPI.jl
  src/RoME.jl
  src/entities/RobotDataTypes.jl
  src/entities/SpecialDefinitions.jl
  src/factors/RangeAzimuthElevation.jl
  src/factors/SensorModels.jl
  src/legacy/BayesTracker.jl
  src/legacy/CameraModel.jl
  src/legacy/NavigationSystem.jl
  src/legacy/Slam.jl
  src/services/AdditionalUtils.jl
  src/services/BearingRangeUtils.jl
  src/services/FactorGraphAnalysisTools.jl
  src/services/FixmeManifolds.jl
  src/services/ManifoldUtils.jl
  src/services/OdometryUtils.jl
  src/services/RobotUtils.jl
  src/services/SimulationUtils.jl
  src/services/g2oParser.jl
  test/testPose3.jl
Labels: release
