Repository JuliaRobotics/RoME.jl, pull requests merged in 2023-09, with the labels that each got.

#698 ins equation via DERelative factor
  test/inertial/testODE_INS.jl
Labels: needs testing, factors, inertial

#699 general maintenance
  Project.toml
  test/testPartialPose2.jl
Labels: maintenance, compat, bug fix

#700 Fix and add basic test for ins kinematic eq
  test/inertial/testODE_INS.jl
Labels: differential equations, imu
