Repository JuliaRobotics/RoME.jl, pull requests merged in 2023-10, with the labels that each got.

#703 test fix for IIF 1776
  test/testBearingRange2D.jl
Labels: testing, bug fix

#704 Updates for upstream parametric optim to manopt change
  ext/RoMEFluxExt.jl
  src/factors/BearingRange2D.jl
  src/factors/DynPose2D.jl
  src/factors/InertialPose3.jl
  src/factors/MutablePose2Pose2.jl
  src/factors/Point3D.jl
  src/factors/Pose2D.jl
  src/factors/Pose3D.jl
  src/factors/Pose3Pose3.jl
  src/factors/PriorPose2.jl
  src/factors/VelPose2D.jl
  src/services/g2oParser.jl
  test/testParametric.jl
  test/testPose3.jl
Labels: standardization, parametric solution, performance, maintenance

#705 drop JLD2 dep
  Project.toml
  src/RoME.jl
Labels: compat, dependencies, breaking changes

#701 IMU Lie Group pre-integration factor
  src/RoME.jl
  src/factors/Inertial/IMUDeltaFactor.jl
  test/inertial/testIMUDeltaFactor.jl
  test/runtests.jl
Labels: needs testing, factors, inertial

#709 Updates for ManifoldsBase v0.15
  Project.toml
  src/RoME.jl
  src/factors/PriorPose2.jl
  src/factors/Range2D.jl
  src/services/FixmeManifolds.jl
  test/runtests.jl
  test/testPartialPose3.jl
Labels: compat

#712 Add compat for std libraries
  Project.toml
Labels: maintenance, toml, compat

#713 v0.24-rc1
  Project.toml
Labels: release
