Repository JuliaRobotics/RoME.jl, pull requests merged in 2024-08, with the labels that each got.

#746 various minor updates
  src/ExportAPI.jl
  src/RoME.jl
  src/factors/Inertial/IMUDeltaFactor.jl
  src/services/ManifoldUtils.jl
  test/inertial/testIMUDeltaFactor.jl
Labels: enhancement

#738 Pose3Pose3Transform Factor
  src/factors/Pose3Pose3.jl
Labels: factors

#747 use ApproxManiProds.skew instead
  Project.toml
  src/factors/Inertial/IMUDeltaFactor.jl
Labels: bug fix

#748 add VelPos3 variable and factors
  src/ExportAPI.jl
  src/RoME.jl
  src/factors/Inertial/IMUDeltaFactor.jl
  src/factors/Inertial/PriorIMUBias.jl
  src/factors/PriorVelPos3.jl
  src/factors/VelPosRotVelPos.jl
  src/variables/VariableTypes.jl
  test/runtests.jl
  test/testVelPos3.jl
Labels: enhancement, testing, factors, serialization, variableType, imu

#749 fix IMUDelta factor serde
  src/ExportAPI.jl
  src/factors/Inertial/IMUDeltaFactor.jl
Labels: serialization, bug fix, workaround

#750 refactor sensor extrinsics type
  src/ExportAPI.jl
  src/RoME.jl
  src/factors/VelAlign.jl
Labels: enhancement, standardization, refactoring, factors

#751 RC v0.24.5
  .github/workflows/TagBot.yml
  Project.toml
  src/ExportAPI.jl
  src/RoME.jl
  src/factors/Inertial/IMUDeltaFactor.jl
  src/factors/Inertial/PriorIMUBias.jl
  src/factors/Pose3Pose3.jl
  src/factors/PriorVelPos3.jl
  src/factors/VelAlign.jl
  src/factors/VelPosRotVelPos.jl
  src/services/ManifoldUtils.jl
  src/variables/VariableTypes.jl
  test/inertial/testIMUDeltaFactor.jl
  test/runtests.jl
  test/testVelPos3.jl
Labels: release
